version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py add_fixtures db_test_initial.json &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
  dev-data: