# Generated by Django 3.2.16 on 2022-10-28 15:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('model', models.IntegerField(choices=[(0, 'Lightwheight'), (1, 'Middlewheight'), (2, 'Cruiserwheight'), (3, 'Heavywheight')], default=0)),
                ('weight_limit', models.IntegerField(default=500, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('battery', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('state', models.IntegerField(choices=[(0, 'Idle'), (1, 'Loading'), (2, 'Loaded'), (3, 'Delivering'), (4, 'Delivered'), (5, 'Returning')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
