# Generated by Django 3.2.16 on 2022-10-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_drone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='model',
            new_name='drone_model',
        ),
    ]
