# Generated by Django 3.2.16 on 2022-10-29 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221029_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(message='Only uppercase, numbers and underscore.', regex='\\b[A-Z0-9_]+\\b')]),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(message='Only Alphanumeric, underscore and score.', regex='\\b[a-zA-Z0-9_-]+\\b')]),
        ),
    ]
