# Generated by Django 3.2.16 on 2022-10-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_model_drone_drone_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='drone_model',
            field=models.IntegerField(choices=[(0, 'Lightweight'), (1, 'Middleweight'), (2, 'Cruiserweight'), (3, 'Heavyweight')], default=0),
        ),
    ]
