# Generated by Django 3.2.16 on 2022-10-30 20:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_drone_weight_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.medication_image_file_path),
        ),
    ]
