# Generated by Django 3.2.16 on 2022-10-29 04:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_drone_drone_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(message='Only uppercase, numbers and underscore.', regex='(A-Z0-9_)+')])),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(message='Only Alphanumeric, underscore and score.', regex='(A-z0-9_-)+')])),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='drone',
            name='medications',
            field=models.ManyToManyField(to='core.Medication'),
        ),
    ]
