---
name: Checks

on: [push]

env:
  DJANGO_SECRET_KEY: changeme
  DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
  DEBUG: 1
  POSTGRESS_DB: devdb
  POSTGRES_USER: devuser
  POSTGRESS_PASSWORD: changeme

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"